### PR TITLE
fix: fix iter over table with zero as key

### LINKED ISSUE #114: Bug in pairs implementations
The following code causes an infinite loop

```lua
do
    local t = {[0]=0, [1]=1, [2]=2}
    local s = ""
    for _, x in pairs(t) do
        s = s..x
    end
    print(s)
    --> =120
end
```

See #113

### PR DESCRIPTION
**Pull request by vaniog**
I'm not sure is it the right fix, and i'm not sure i properly tested it.

But there is definitely a problem. A test i wrote in `table.lua` gets into infinite loop, because `next` calls are cycled.

Maybe it's worth adding this even in lua official testsuite? The order is unspecified, but it definitely must not gets into infinite loop.

### CODE REVIEW

**Comment by vaniog** [comment]
And i want to thank you deeply! \
There are a few go libraries which implement lua interpreter, but it is the only one, which can limit memory and cpu!

With it we build a game hackathon for schoolchildren. They wrote snake strategies with lua, and strategies competed in automatic matches. Also there was a builtin website playground (go compiled to wasm), and people could run simulations even on client! You saw my issue about wasm :)

And current problem (iterating over table with `0` key) came up then i tested this:
```lua
local directions = {
    [0] = {x = 0, y = -1},
    [1] = {x = 1, y = 0},
    [2] = {x = 0, y = 1},
    [3] = {x = -1, y = 0}, 
}

for _, d in ipairs(directions) do
   ...
end
```

I think it is a quite fun story and worth sharing :)

https://github.com/user-attachments/assets/a4c50a0d-1fa1-4e13-8cf4-2663ce491834

**Comment by arnodel** [comment]
Thank you!  I've reproduced the bug and created #114 .  I'll look into it asap.  Your scriptable snake project looks really cool!  Many years ago I created a game where people had to solve a maze game (collect all the flags in the maze) by programming a robot: http://marooned.org.uk/robo/static/robo.html. (it's very old).

File: runtime/hashtable.go [hunk 1]
```diff
@@ -119,6 +119,9 @@ func (t *mixedTable) next(k Value) (next Value, v Value, ok bool) {
 		isInt = true
 	} else {
 		i, isInt = ToIntNoString(k)
+		if isInt && i == 0 {
+			return t.hashTable.next(IntValue(0))
+		}
```
Comment (arnodel) [inline runtime/hashtable.go]: I think this is slightly better:

```suggestion
		if isInt && i <= 0 {
			isInt = false
		}
```

**Review by arnodel — CHANGES_REQUESTED** [review]
Thanks for the PR!  I'm suggesting a slightly improved way to fix it.  We could also add some tests in hashtable_test.go (but that's optional)

**Comment by vaniog** [comment]
> Thanks for the PR! I'm suggesting a slightly improved way to fix it. We could also add some tests in hashtable_test.go (but that's optional)

I think it's already enough. Tests in `hashtable_test.go` are small, let them stay that way.

**Comment by vaniog** [comment]
> Thank you! I've reproduced the bug and created #114 . I'll look into it asap. Your scriptable snake project looks really cool! Many years ago I created a game where people had to solve a maze game (collect all the flags in the maze) by programming a robot: http://marooned.org.uk/robo/static/robo.html. (it's very old).

Wow, its really old, 14 years ago I just started school...
Badass design with pure html btw.

**Review by arnodel — APPROVED** [review]
Looks good!  Many thanks for reporting and fixing the issue.
